name: veeru

on: workflow_dispatch
#  pull_request:
#  push:
#    branches:
#      - master
#      - develop
#      - feature/**
#    tags:
#      - '**'

jobs:

  b2-windows:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - name: Setup Boost
        shell: cmd
        run: |
          cmd /c bootstrap
          b2 -d0 headers

      - name: Build Boost
        run: |
          ./b2 -j3 stage

      - name: Install Boost
        run: |
          ./b2 -j3 install

      - name: Test Boost
        run: |
          cd status
          ../b2 -j3 quick

  b2-cmake-tool-windows:
    strategy:
      fail-fast: false
      matrix:
        tool:
          - boostdep
          - inspect
          - quickbook

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - name: Install Boost
        shell: cmd
        run: |
          cmd /c bootstrap
          b2 -j3 --with-filesystem --with-regex --with-program_options install

      - name: Build tool with CMake
        run: |
          cmake -S tools/${{matrix.tool}} -B __build__ -DBoost_ROOT=C:/Boost -DCMAKE_INSTALL_PREFIX=C:/usr/local
          cmake --build __build__ --target install --config Release

  cmake-install-windows:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - name: Configure Boost
        run: |
          mkdir __build__ && cd __build__
          cmake -DBUILD_SHARED_LIBS=ON ..

      - name: Build Boost
        run: |
          cd __build__
          cmake --build . -j 3

      - name: Install Boost
        run: |
          cd __build__
          cmake --build . -j 3 --target install

  cmake-test-windows-quick:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - name: Configure Boost
        run: |
          mkdir __build__ && cd __build__
          cmake -DBUILD_TESTING=ON ..

      - name: Build tests
        run: |
          cd __build__
          cmake --build . -j 3 --target tests-quick

      - name: Run tests
        run: |
          cd __build__
          ctest --output-on-failure --no-tests=error -j 3 -R quick -C Debug
